title: MARLIN
description: Malaria ANC-based Reconstructions with Learning-based Inference using Neural networks
baseurl: "/MARLIN"
url: "https://olatundemi.github.io"

# Layout and CSS
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# SCSS/CSS
sass:
  sass_dir: assets/css
  style: compressed

# Markdown processor
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# GitHub Pages specific
github: [metadata]

# Build settings
source: .
destination: _site
keep_files: [.git]

# Exclude files
exclude:
  - readme.md
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - "*.pycache"
  - __pycache__
